# Build stage
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["TextEditor.csproj", "."]
RUN dotnet restore "TextEditor.csproj"
COPY . .
RUN dotnet build "TextEditor.csproj" -c Release -o /app/build
RUN dotnet publish -c Release -o out
RUN dotnet tool restore
RUN dotnet tool install --global dotnet-ef --version 3.1
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet ef migrations add InitialCreate
RUN dotnet ef database update

# Publish stage
FROM build AS publish
RUN dotnet publish "TextEditor.csproj" -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TextEditor.dll"]
