pipeline:
  name: poc
  identifier: poc
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub
        repoName: .NET_POC
        build: <+input>
  stages:
    - stage:
        name: Docker
        identifier: Docker
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: GitHub
                    repoName: .NET_POC
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Database Build
                  identifier: Database_Build
                  spec:
                    connectorRef: Dockerhub
                    repo: eatherv/database
                    tags:
                      - latest
                    dockerfile: ./TextEditor/database/
